### ISSUE TITLE
No Response When Checking Compliance 

### ISSUE THREAD

**Issue by alexey86i** [lavaloon-eg/ksa_compliance#119]
Hello,

After filling all the necessary data and generating the CSR using OTP for Simulation, clicking on the "Perform Compliance Checks" results in nothing... No message appears on whether or not the checks have been performed and what the results were. No errors or reports or anything...

**Comment by alexey86i** [comment]
Talking to a colleague, they mentioned that they did face the same issue before but they went ahead and tried submitting an invoice while in simulation mode regardless and were successful in doing so.
Decided to try it out and see what would happen. Keep getting the following error every time I try to submit an invoice:

> ZATCA CLI Error
> Certificate file does not exist: /home/infoway/frappe-bench/sites/310796080100003.pem

**Comment by mhaggag** [comment]
Hello,

Getting the production CSID generates the certificate file that's missing. Regarding compliance: Can you check whether you have any errors in logs/zatca.log or the `Error Log` list when you perform compliance?

**Comment by alexey86i** [comment]
zatca.log file attached
[zatca.log](https://github.com/user-attachments/files/17015378/zatca.log)

**Comment by alexey86i** [comment]
Yes, there is.

**Comment by mhaggag** [comment]
Is the `Tax Category` set on the default `Sales Taxes and Charges Template`?

![image](https://github.com/user-attachments/assets/4ed37b90-e793-4214-96d8-49dd05136263)

**Comment by alexey86i** [comment]
The "Default" was checked but the "Tax Category" was not set. Tried setting it and attempted a compliance check but still no message showing.

![image_2024-09-16_185850525](https://github.com/user-attachments/assets/39dc9aa1-adca-400c-a025-82a59fd330ef)

**Comment by mhaggag** [comment]
Can you check the error log after setting the tax category? Also, please make sure the tax category has a set `ZATCA Category`

![image](https://github.com/user-attachments/assets/f6360852-2497-4c8b-80f6-5e9286ea64fe)

There's a PR (#120) that fixes the problem of not showing errors during compliance, but it looks like there are several cases that aren't properly checked and they report the same error (the one about setting a default sales taxes and charges template), so we'll address those as we figure them out.

**Comment by alexey86i** [comment]
Following are the latest logs:

zatca.log
[zatca (1).log](https://github.com/user-attachments/files/17016610/zatca.1.log)

Compliance error
[Compliance error_2.txt](https://github.com/user-attachments/files/17016618/Compliance.error_2.txt)

Simplified Compliance Check Result
[Simplified Compliance Check Result.txt](https://github.com/user-attachments/files/17016619/Simplified.Compliance.Check.Result.txt)

Standard Compliance Check Result
[Standard Compliance Check Result.txt](https://github.com/user-attachments/files/17016621/Standard.Compliance.Check.Result.txt)

Also Tax Category has  a ZATCA Category set.
![opera_rhFqTvCBbw](https://github.com/user-attachments/assets/9b8c9736-37c7-4080-9989-2d8cf3b18442)

**Comment by mhaggag** [comment]
I'm assuming you got a compliance progress dialog this time, followed by a message saying everything was rejected and linking to error logs. Is that correct?

The logs indicate we went through the compliance steps and all submissions were rejected due to an unknown error. However, they also indicate we were signing with the sandbox private key, which is the case for the sandbox environment only (not simulation or production). Can you confirm whether you're in sandbox or simulation? For sandbox, you need to use the VAT number `399999999900003` specifically in the `Seller ID` tab before going through integration (onboarding, compliance, and production CSID)

**Comment by alexey86i** [comment]
Latest results.

[Simplified Compliance Check Result_2.txt](https://github.com/user-attachments/files/17017299/Simplified.Compliance.Check.Result_2.txt)

[Standard Compliance Check Result_2.txt](https://github.com/user-attachments/files/17017306/Standard.Compliance.Check.Result_2.txt)

[zatca (2).log](https://github.com/user-attachments/files/17017308/zatca.2.log)

Also not sure if it would help but here's a look at how the settings look right now.
[Settings.pdf](https://github.com/user-attachments/files/17017315/Settings.pdf)

**Comment by mhaggag** [comment]
There is a warning caused by country code being `sa` instead of `SA` (upper-case). This can be updated in the country.

The error is something we observed today, and we're assuming it's a result of the latest ZATCA SDK update (3.3.5) because submissions were working fine on 3.3.4. I don't think we have reached a conclusion as to what was causing it. @omarashrafsarhan was investigating it today and can weigh in with his latest findings.

The error is vague, likely an internal exception since there's no error code. Just "Unable to execute Business Rules validation ->"; it looks like some code or cause was supposed to be appended but wasn't. We're not seeing this error on sandbox or production either.

We'll update our CLI to use the new SDK and see if we can reproduce the problem.

**Comment by alexey86i** [comment]
Country code changed to SA.

Latest logs after change:
[Standard Compliance Check Result_3.txt](https://github.com/user-attachments/files/17019019/Standard.Compliance.Check.Result_3.txt)
[Simplified Compliance Check Result_3.txt](https://github.com/user-attachments/files/17019020/Simplified.Compliance.Check.Result_3.txt)
[zatca (3).log](https://github.com/user-attachments/files/17019021/zatca.3.log)

Also, still no progress dialog even after making sure only one tab is open for the instance.

Appreciate all your support on this. Thank you very much.

**Comment by mhaggag** [comment]
Re: progress dialog. What happens after you start the compliance check? Do you get no UI indication at all that something is happening? We're using frappe's [realtime API](https://frappeframework.com/docs/user/en/api/realtime#frappe-publish-progress) to show the progress dialog, so if it's not showing it could indicate a problem with the socket support. Do progress dialogs work in this instance? Perhaps try to do a bulk update or a similar process that shows a progress dialog to check.

Regarding the main problem, we think we figured out the problem based on [this discussion](https://zatca1.discourse.group/t/business-rules-error-for-multiple-partyidentification-tags/1154); it says putting multiple seller IDs is wrong. This is a bug in the app, because we put all the IDs you specify in the `Seller ID` tab into the XML.

We need to test after clearing the 700 number. Unfortunately, that can only be done from the database (using SQL) currently. Clearing it from Desk makes it blank instead of null, and will still insert it into the XML. Data import is also disabled for the `ZATCA Business Settings` doctype.

If you have access to the database console, you need to do something like this in `bench mariadb`:

First a query to get the ID of the row:
```
MariaDB [erp-einvoice-test]> select name, type_name, value from `tabAdditional Seller IDs` WHERE parent = 'Demo for ZATCA-Saudi Arabia-SAR';
+------------+--------------------------------+-----------------+
| name       | type_name                      | value           |
+------------+--------------------------------+-----------------+
| 290c608e74 | Other OD                       | NULL            |
| c1ae474e5e | MOMRAH License                 | NULL            |
| de8d98db2c | 700 Number                     |                 |
| e00d72e78c | MISA License                   | NULL            |
| e4354450df | Commercial Registration Number | 399999999900003 |
| f45aa9b360 | MHRSD License                  | NULL            |
+------------+--------------------------------+-----------------+
6 rows in set (0.001 sec)
```

As you can see in this case I'd cleared the 700 number from Desk and its value is blank instead of NULL. So I run the next query:

```
MariaDB [erp-einvoice-test]> UPDATE `tabAdditional Seller IDs` SET value = NULL WHERE name = 'de8d98db2c';
Query OK, 1 row affected (0.002 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

Now I'm able to pass compliance and generate invoices.

**Comment by mhaggag** [comment]
Forgot to say, we're working on a fix for both issues (not being able to clear seller IDs, and the erroneous inclusion of multiple IDs in the XML)

**Comment by alexey86i** [comment]
I am getting no progress dialogs for anything. It seems like a system-wide thing.

NULL ed the 700 number from the database and following are the latest logs.
[Standard Compliance Check Result_4.txt](https://github.com/user-attachments/files/17025540/Standard.Compliance.Check.Result_4.txt)
[Simplified Compliance Check Result_4.txt](https://github.com/user-attachments/files/17025542/Simplified.Compliance.Check.Result_4.txt)
[zatca (4).log](https://github.com/user-attachments/files/17025555/zatca.4.log)

Thank you once again for all your help.

**Comment by mhaggag** [comment]
Simplified invoice compliance is OK now. For standard, the customer appears to have an invalid vat registration number. Note that the app is currently using a custom field (custom_vat_registration_number) instead of the standard tax ID field, so please check its value. Also there’s a bunch of warnings regarding customer address that aren’t blocking but should be fixed.

**Comment by alexey86i** [comment]
After going through the log I I guess it is starting to make more sense I am starting to recognize the different things being reported.
I am in the process of testing with a new customer being created to fulfill all the needed information.

Will report soon.

**Comment by omarashrafsarhan** [comment]
Hello,

You need to add the customer address in the proper structure,

- Address line 1
- Building number must be 4 digits
- The district
- The city
- The postal code Must be 5 digits

**Comment by alexey86i** [comment]
Latest Log.

[Standard Compliance Check Result_6.txt](https://github.com/user-attachments/files/17026323/Standard.Compliance.Check.Result_6.txt)

**Comment by omarashrafsarhan** [comment]
If you are using sandbox for testing, we recommend using the simulation first before the production because the sandbox still not considering all the parameters you can test on the simulation first to make sure everything is fine then proceed to production

**Comment by alexey86i** [comment]
I was doing all the latest tests in Simulation. All the reports I submitted today were produced in Simulation mode.
Would you advise moving on to the Production instance and replicating everything there based on that?
So far I was experimenting in different instance I've fired up for testing only.

**Comment by omarashrafsarhan** [comment]
If you checked, your business process and the created transactions and the required configuration on the simulation it's fine you can proceed the simulation is mirror to the production behavior on ZATCA platform, but the sandbox not considering some information like the VAT registration must be a real number or the sequence of the invoices

**Comment by alexey86i** [comment]
Thank you very much for all the support. Much Appreciated.

**Comment by omarashrafsarhan** [comment]
We appreciate your feedback. Should you have any additional questions or concerns, please feel free to reach out to us at any time.

I will proceed with closing this issue now.
